env:
  browser: true
  es2020: true
extends:
  - 'plugin:prettier/recommended'
  # - 'plugin:react/recommended'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
  - unused-imports
rules:
  sort-imports: 0
  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  no-restricted-imports:
    - error
    - patterns:
        - '@material-ui/*'
  # '@typescript-eslint/no-unused-vars': off
  # unused-imports/no-unused-imports-ts: error
  # unused-imports/no-unused-var-ts:
  #   - warn
  #   - wars: 'all'
  #     varsIgnorePattern: '^_'
  #     args: 'after-used'
  #     argsIgnorePattern: '^_'
  # react/jsx-uses-react: 1
  # react/jsx-uses-vars: 1
overrides:
  - files:
      - '**/*.tsx'
    rules:
      react/prop-types: 'off'
  - files:
      - '**/*.js'
    rules:
      prettier/prettier: 'off'
