env:
  browser: true
  es2020: true
extends:
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
  - unused-imports
rules:
  sort-imports: 0
  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  no-restricted-imports:
    - error
    - patterns:
        - '@material-ui/*'
overrides:
  - files:
      - '**/*.tsx'
    rules:
      react/prop-types: 'off'
  - files:
      - '**/*.js'
    rules:
      prettier/prettier: 'off'
